### ISSUE TITLE
contract ABI gen

### ISSUE THREAD

**Issue by panos-xyz** [ontio/ontology-wasm-cdt-rust#101]
how can I generate contract ABI?

**Comment by laizy** [comment]
Automatic ABI generation is not supported. And in our practice, it works well without that. what is your use case?

**Comment by panos-xyz** [comment]
I would like to refer to this project to implement a wasm contract library, but it is found that ABI has not been generated.
If ABI cannot be generated automatically, how can I send transactions to encode and decode data on the SDK side without ABI?

**Comment by laizy** [comment]
for common types like `Address, U128，H256, String`, the SDK will encode that for you. so a wasm contract has the following sig:
```rust
pub fn initialize(owner: &Address, underlying_name: &str,  amount : U128){}
```
transaction can be constructed using go sdk like:
```go
var owner Address
underlyingName := "name"
amount:= 1000
ontSdk.WasmVM.InvokeWasmVMSmartContract(
		gasprice, invokegaslimit, nil, signer, contractAddr, "initialize", []interface{}{owner, underlyingName, amount})
```

**Comment by panos-xyz** [comment]
Thanks i understand
