### ISSUE TITLE
Suggestion: Rename repository

### ISSUE THREAD

**Issue by jonatanblockchain** [ontio/ontology-wasm-cdt-rust#36]
What do you think about rename the repository per `ontology-wasm-cdt-rust`? We maintain a similar name like EOS repository's (cdt) but specifying the language.

Same when c and cpp will be ready. `ontology-wasm-cdt-ccpp` @carltraveler

**Comment by laizy** [comment]
we have intended to give it a more specific name,  but not found yet. what do you think? @carltraveler
