### ISSUE TITLE
build token and the wasm file is too large wasm

### ISSUE THREAD

**Issue by hunjixin** [ontio/ontology-wasm-cdt-rust#42]
after build and stript the ope8token  contract ,and the wasm is 33kb, its too big, nearly tenfold of erc20

**Comment by laizy** [comment]
since the contract contains memory allocation logic and big int simulation code, so it will be a little larger for simple contract, but for complex contract the size will be negligible. 
The wasm file size for oep8token we generate is about 8K, so  can you supply your build script or wasm file?

**Comment by hunjixin** [comment]
file is in example [https://github.com/ontio/ontology-wasm-cdt-rust/tree/master/examples/oep8token](https://github.com/ontio/ontology-wasm-cdt-rust/tree/master/examples/oep8token)
script:
toml
```
[package]
name = "oep8token"
version = "0.1.0"
authors = ["lucas7788 <sishsh@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ontio-std = {path="../../ontio-std"}

[profile.release]
lto = true
opt-level = 'z'

[features]
mock = ["ontio-std/mock"]
```
```
cargo build --release --target wasm32-unknown-unknown
```
here  the size is 462kb


```
wasm-strip oep8token.wasm
```
size reduce to 33kb

```
wasm-opt -Oz oep8token.wasm -o oep8token2.wasm
```
oep8token2.wasm is 27kb

**Comment by hunjixin** [comment]
[oep8token2.zip](https://github.com/ontio/ontology-wasm-cdt-rust/files/3002523/oep8token2.zip)
here is the final wasm

**Comment by laizy** [comment]
sorry, revise what I said before, the wasm file size we generated is the same as yours. After some analysis with [twiggy](https://github.com/rustwasm/twiggy), the size expansion mostly comes from `abi::Dispatcher` using  code generation. we will optimize this part soon.

**Comment by laizy** [comment]
close since many existing projects(like [Wing Finance](https://wing.finance/)) have shown that the size of the contract is not a limiting factor.
